// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWA_yqLDJMBE8gGCCXy2MNpgiPwXsF6Ls',
    appId: '1:386409542958:web:2abe82417b168ab58e76bf',
    messagingSenderId: '386409542958',
    projectId: 'lista-tarefas-projeto-v1',
    authDomain: 'lista-tarefas-projeto-v1.firebaseapp.com',
    storageBucket: 'lista-tarefas-projeto-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvospQ0brBG79k2LBLo4bOX4U44s5UAlY',
    appId: '1:386409542958:android:6ece78b61c8158168e76bf',
    messagingSenderId: '386409542958',
    projectId: 'lista-tarefas-projeto-v1',
    storageBucket: 'lista-tarefas-projeto-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Kp5t02ZYsqyQ6Mmq2pQChb_Pcrj51FU',
    appId: '1:386409542958:ios:15cc1857864fc4418e76bf',
    messagingSenderId: '386409542958',
    projectId: 'lista-tarefas-projeto-v1',
    storageBucket: 'lista-tarefas-projeto-v1.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Kp5t02ZYsqyQ6Mmq2pQChb_Pcrj51FU',
    appId: '1:386409542958:ios:15cc1857864fc4418e76bf',
    messagingSenderId: '386409542958',
    projectId: 'lista-tarefas-projeto-v1',
    storageBucket: 'lista-tarefas-projeto-v1.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWA_yqLDJMBE8gGCCXy2MNpgiPwXsF6Ls',
    appId: '1:386409542958:web:ed00c10b1cdd8bc88e76bf',
    messagingSenderId: '386409542958',
    projectId: 'lista-tarefas-projeto-v1',
    authDomain: 'lista-tarefas-projeto-v1.firebaseapp.com',
    storageBucket: 'lista-tarefas-projeto-v1.firebasestorage.app',
  );
}
